### PR TITLE
Add output of "rabbitmqctl report" to susecloud plugin

### PR DESCRIPTION
**Pull request by mjura**
This change was cherry-picked from :
    (cherry-picked from 8b0d0af492551fe8421e991b077b23509c97fa61)
    (cherry-picked from 26c455532ad984e2baea4a7bf41f549c5c937f5d)
    (cherry-picked from 76e4a8348d3dd77a89d8a19ed806ad5cac7c2c21)

### CODE REVIEW

**Comment by vuntz** [comment]
Please cherry-pick the commits without squashing them.

**Comment by mjura** [comment]
@vuntz: As you wish, I was wondering in which way will be better.

**Comment by vuntz** [comment]
+1.

@mjura: when backporting, cherry-picking is always better :-)

**Comment by dirkmueller** [comment]
@mjura you cherry-picked the merges. can you cherry pick the commits instead please?

**Comment by mjura** [comment]
@dirkmueller: Should be ok now

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
