### PR TITLE
double log lines to capture from 5,000 to 10,000 

### PR DESCRIPTION
**Pull request by aspiers**
Also do a quick refactoring.

### CODE REVIEW

**Comment by aspiers** [comment]
This is failing because I enabled Travis CI and #53 isn't merged yet, so it's trying to run `rake` which is default Travis gating behaviour.

**Comment by aspiers** [comment]
Rebased and now Travis passes :)

**Comment by jsuchome** [comment]
+1

**Comment by abel-navarro** [comment]
+1

**Pull request merged**
