### PR TITLE
Fix export chef data when crowbar installed ok

### PR DESCRIPTION
**Pull request by mjura**

### CODE REVIEW

**Comment by aspiers** [comment]
+1, I'm assuming this is correct ;-)

**Comment by rsalevsky** [comment]
+1

**Comment by dirkmueller** [comment]
Looks correct, this was changed in crowbar: https://github.com/crowbar/crowbar/commit/bc053c8e714946b3c5c301d6dc8d9797165309da

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
