### PR TITLE
fix whitespace and set upTravis to check with bashate

### PR DESCRIPTION
**Pull request by aspiers**
It's sad that we need CI to enforce correct indentation levels, but at least bashate brings us plenty of other nice checks.

### CODE REVIEW

**Comment by aspiers** [comment]
OK this is ready for review / merge now.

**Comment by aspiers** [comment]
@jsuchome @abel-navarro This is straight-forward - please could you review?

**Comment by aspiers** [comment]
All new PRs will incur Travis failures until this is merged.  #54 is the first example.

**Comment by jsuchome** [comment]
Makes sense and I do not see any error. +1

**Comment by abel-navarro** [comment]
LGTM +1

I'm good with this change in coding style, since previously there wasn't any for bash scripts afaik. I do wonder if everyone in the team will agree to enforce this.

**Comment by tboerger** [comment]
> I'm good with this change in coding style, since previously there wasn't any for bash scripts afaik. I do wonder if everyone in the team will agree to enforce this.

It is already used within crowbar/crowbar quite long, even if I don't like this python thing for that ;)

**Pull request merged**
